/* Page 2 only: GIS Components (continued), based on the supplied lesson page. */
(() => {
  const bank = [];
  const add = (id, type, topic, prompt, answer, explanation, extra = {}) => bank.push({id: 'p2-' + id, type, topic, prompt, answer, explanation, ...extra});
  const identify = (id, topic, prompt, answer, explanation, aliases = []) => add(id, 'fill', topic, prompt, answer, explanation, {aliases});
  const tf = (id, topic, prompt, truth, explanation) => add(id, 'tf', topic, prompt, truth ? 'True' : 'False', explanation, {options: ['True', 'False']});
  const mc = (id, topic, prompt, answer, distractors, explanation) => add(id, 'mc', topic, prompt, answer, explanation, {options: [answer, ...distractors]});
  identify('i1','Software','The GIS component that provides tools to store, analyze, and display geographic information.','Software','Software provides the programs and tools used in GIS.');
  identify('i2','Software','The software component used to manage stored data.','Database Management System','A database management system manages stored data.',['DBMS','database system','database']);
  identify('i3','Software','The software tools used to enter and modify geographic information.','Input and manipulation tools','Input enters data; manipulation modifies it.',['tools for input and manipulation','input and manipulation','data input and manipulation tools','tools for the input and manipulation of geographic information']);
  identify('i4','Software','The software tools that support asking geographic questions, analyzing data, and displaying results.','Query, analysis, and visualization tools','These tools help users ask questions, study data, and show results.',['query analysis and visualization','query analysis visualization tools','tools for query analysis and visualization','geographic query analysis and visualization tools']);
  identify('i5','Software','The visual interface that gives users easy access to GIS tools.','Graphical User Interface','A GUI provides visual controls for accessing tools.',['GUI','graphical interface']);
  identify('i6','Software','The full meaning of the abbreviation GUI.','Graphical User Interface','GUI stands for Graphical User Interface.');
  identify('i7','People','The GIS component made up of those who design, manage, sell, and use GIS applications.','People','GIS users include technicians and specialists.');
  identify('i8','Methods','The GIS component consisting of plans and business rules for applying GIS technology.','Methods','Methods describe how GIS should be applied.',['methods/applications','methods and applications']);
  identify('i9','Data','The GIS component that supplies the geographic facts and information needed for analysis.','Data','Data supplies the information GIS needs to produce useful results.');
  identify('i10','Data','The related data that describe the qualities of geographic features.','Attribute data','Attribute data describes features, such as a road name or the number of rooms in a building. It can be organized in tables.',['tabular data','attribute','attributes','tabular or attribute data']);
  identify('i11','Data','The way of obtaining data by collecting it within the organization itself.','In-house collection','In-house means the organization collects the data itself.',['in house','collected in house','in house data collection','collecting in house']);
  identify('i12','Data','The organized collection of data that most GISs maintain to help manage information.','Database','A database helps organize and manage data.');
  tf('t1','Software','GIS software provides tools for storing, analyzing, and displaying geographic information.',true,'GIS software provides tools to store, analyze, and display geographic information.');
  tf('t2','Software','A GUI provides easy access to GIS tools.',true,'GUI means Graphical User Interface.');
  tf('t3','Software','Input and manipulation tools are used only to display finished results.',false,'They enter and modify geographic information.');
  tf('t4','People','GIS users can include technicians and specialists.',true,'Different people use GIS in their everyday work.');
  tf('t5','People','People only use GIS applications; they do not design or manage them.',false,'People design, manage, sell, and use GIS applications.');
  tf('t6','Methods','Methods include guidelines, specifications, standards, and procedures.',true,'These four items guide how GIS is applied.');
  tf('t7','Methods','Methods are the physical computers and devices used in GIS.',false,'Methods are plans and rules. Physical devices are hardware.');
  tf('t8','Data','GIS needs geographic data to analyze places and the features found there.',true,'Data provides the geographic facts and information used in GIS analysis.');
  tf('t9','Data','All GIS data must be bought from a commercial provider.',false,'Data can also be collected in-house.');
  tf('t10','Data','Most GISs maintain a database to organize and manage data.',true,'A database helps keep data organized.');
  mc('m1','Software','An example of GIS software used to store, analyze, and display geographic information.','QGIS',['GPS','Scanner','Plotter'],'QGIS is GIS software. GPS is a positioning system; scanners and plotters are hardware.');
  mc('m2','Software','The correct meaning of GUI.','Graphical User Interface',['Geographic User Information','General Utility Input','Geographic Unit Interface'],'A Graphical User Interface gives easy access to tools.');
  mc('m3','Software','The software component that manages stored data.','Database management system',['Graphical user interface','Input tools','Visualization tools'],'A database management system manages data.');
  mc('m4','Software','The tools used to enter and change geographic information.','Input and manipulation tools',['Query and visualization tools','Output devices','Guidelines and standards'],'Input enters information; manipulation modifies it.');
  mc('m5','People','The GIS component represented by a technician using GIS at work.','People',['Software','Methods','Data'],'The technician is a user, so the component is People.');
  mc('m6','Methods','The GIS component that provides plans and rules for applying GIS technology.','Methods',['Software','Data','Hardware'],'Methods provide plans, rules, and procedures.');
  mc('m7','Methods','The list of items included in GIS methods.','Guidelines, specifications, standards, procedures',['GPS, scanners, cameras, printers','Maps, coordinates, images, attributes','Input, query, analysis, visualization'],'The four methods items guide GIS work.');
  mc('m8','Data','The GIS component that provides the information used to create maps and perform analysis.','Data',['Hardware','Software','Methods'],'Data includes the geographic information used to create maps and analyze places.');
  mc('m9','Data','The two ways an organization can obtain geographic data for use in GIS.','In-house collection and commercial providers',['Printers and plotters','Technicians and monitors','GUI and visualization tools'],'Organizations can collect data themselves or buy it from a provider.');
  mc('m10','Software and methods','The correct difference between software and methods.','Software provides tools; methods explain how to apply them',['Software means users; methods mean devices','Software means data; methods mean maps','Software and methods both mean physical equipment'],'Remember: software = tools; methods = procedures.');
  window.GIS_PAGE2_QUESTIONS = bank;
})();
