/* Essential first-page Lesson 2 concepts. No counting or slogan-completion questions. */
(() => {
  const questions = [];
  function mc(id, topic, prompt, answer, distractors, explanation) {
    questions.push({id, type: 'mc', topic, prompt, answer, options: [answer, ...distractors], explanation});
  }
  function tf(id, topic, prompt, answer, explanation) {
    questions.push({id, type: 'tf', topic, prompt, answer: answer ? 'True' : 'False', options: ['True', 'False'], explanation});
  }
  function fill(id, topic, prompt, answer, aliases, explanation) {
    questions.push({id, type: 'fill', topic, prompt, answer, aliases, explanation});
  }
  mc('m1','Meaning & importance','Which definition best describes a Geographic Information System (GIS)?','Information technology that organizes, analyzes, visualizes, and shares information linked to locations',['A positioning device used only to collect coordinates','A program used only to draw and print maps','A database that stores information without relating it to location'],'GIS connects information to locations and supports organization, analysis, visualization, and sharing. It is broader than a GPS device or a map-drawing program.');
  mc('m2','The five components','Which list correctly identifies the main components of a working GIS?','Hardware, software, data, people, and methods/applications',['Hardware, software, scanners, printers, and GPS','Hardware, maps, data, monitors, and hard drives','Software, data, roads, rivers, and boundaries'],'Learn the components and their roles: hardware = equipment; software = programs; data = information; people = users; methods/applications = procedures and uses.');
  mc('m3','Meaning & importance','Which set of activities describes what GIS does with location-based information?','Organize, analyze, visualize, and share it',['Collect and store it without interpretation','Draw and print it without analysis','Record coordinates without using other information'],'The important functions in these notes are organizing, analyzing, visualizing, and sharing data and information.');
  mc('m4','Meaning & importance','Why does knowing where an event happened help us understand it?','Location provides context for investigating what, when, how, and why it happened',['Location alone proves why the event happened','Location tells us when an event happened without other data','Location matters only when printing the final map'],'Location supplies useful context; it does not prove a cause by itself. This helps us understand our local environment and the wider world.');
  mc('m5','Hardware & devices','Which statement best describes the role of hardware in GIS?','It runs software, stores collected data, and lets people interact with the data',['It is the set of procedures used to conduct a GIS project','It is the information about the locations being studied','It is the computer program that performs the analysis'],'Hardware is physical equipment. The computer runs programs, stores data, and provides a way for users to work with the data.');
  mc('m6','Hardware & devices','A team photographs a site and records positions with GPS. Which hardware category is being used?','Data collection',['Data input','Data output','Data analysis and storage'],'Cameras and GPS gather observations from the real world. The notes group GPS, cameras, and probes under data collection.');
  mc('m7','Hardware & devices','A student scans a paper map, then prints the finished GIS map. How are these devices classified?','Scanner: data input; printer: data output',['Scanner: data collection; printer: data input','Scanner: data output; printer: data analysis and storage','Scanner: data analysis and storage; printer: data collection'],'A scanner inputs data into the system; a printer outputs results. Digitizers are also input devices, while monitors and plotters are output devices.');
  mc('m8','Real-world applications','A health team has disease case records. Which use of GIS would help it understand where cases are concentrated?','Map case locations and analyze their spatial distribution',['List patient names without recording any locations','Print the records without examining where cases occur','Store only the total number of cases for the whole country'],'GIS can organize and display case locations so the team can examine affected areas and spatial patterns.');
  mc('m9','Real-world applications','Which information would GIS need to help you find the nearest supermarket?','Your location and the locations of nearby supermarkets',['Supermarket names and opening dates only','The number of supermarkets, without their locations','Product prices without store locations'],'Finding the nearest place requires location information so distances can be compared.');
  mc('m10','Real-world applications','Which pair of tasks illustrates GIS applications mentioned in your notes?','Tracking a tornado path and recording where a new frog species was found',['Recording wind speeds without locations and counting frog species without locations','Listing storm dates and frog names without connecting either to places','Storing weather totals and species totals without geographic references'],'The geographic connection is essential: where the tornado moved and where the species was discovered.');
  tf('t1','Meaning & importance','GIS is useful only for displaying maps; analyzing geographic information is outside its role.',false,'GIS also organizes, analyzes, and shares information. Map display is one part of what it can do.');
  tf('t2','The five components','A project that has computers, programs, and data already includes every GIS component.',false,'It must also account for people and methods/applications. A working GIS includes users and procedures as well as technology and information.');
  tf('t3','The five components','In a GIS project, the computer is hardware, while the program running on it is software.',true,'Distinguish the physical device (hardware) from its computer programs (software).');
  tf('t4','The five components','The procedures used to carry out GIS work belong to the data component.',false,'Procedures belong to methods/applications. Data are the information used in the work.');
  tf('t5','Hardware & devices','Scanners and digitizers belong to data input, while cameras and probes belong to data collection in your notes.',true,'Input devices enter data into the system. Collection devices gather observations. Keep these categories distinct for your exam.');
  tf('t6','Hardware & devices','A monitor and a plotter are both output devices, even though one displays a result and the other can produce it on paper.',true,'Output can be displayed on a monitor or produced by a printer or plotter.');
  tf('t7','Hardware & devices','A hard drive used to save GIS files belongs to the data output category.',false,'Your notes place computers and hard drives in data analysis and storage. A hard drive stores data.');
  tf('t8','Meaning & importance','Knowing where something happens can help us understand both our local environment and the wider world.',true,'The importance of location extends from local places to the world at large.');
  tf('t9','Real-world applications','A total count of disease cases tells us exactly where those cases are concentrated.',false,'A total does not show distribution. Case locations are needed to examine where cases are concentrated.');
  tf('t10','Real-world applications','Recording the location of a newly discovered frog species connects biological information to a geographic place.',true,'The discovery location makes this an example of geographic information, as described in the lesson.');
  fill('f1','Meaning & importance','Identify the system that organizes, analyzes, visualizes, and shares information linked to locations: ______. Write its full name.','Geographic Information System',['geographical information system'],'The full name is Geographic Information System (GIS). Its defining connection is between information and location.');
  fill('f2','The five components','A GIS computer runs programs, stores data, and lets users interact with it. This physical equipment is the ______ component.','Hardware',[],'Hardware means physical equipment, including the computer and other devices.');
  fill('f3','The five components','The computer program a student uses to work with geographic information belongs to the ______ component.','Software',['computer software'],'Software means computer programs. The computer itself is hardware.');
  fill('f4','The five components','The locations and other information used in a GIS project make up its ______ component.','Data',[],'Data are the information used by GIS. They are distinct from the equipment and programs that handle them.');
  fill('f5','The five components','The students and other users working with a GIS belong to its ______ component.','People',['users'],'People are the users who work with GIS; they are a component alongside hardware, software, data, and methods/applications.');
  fill('f6','The five components','The procedures and ways of applying GIS belong to the ______ component.','Methods/applications',['methods','applications','methods and applications','methods or applications','methods applications'],'Methods/applications describe procedures and uses. They guide how GIS is applied.');
  fill('f7','Hardware & devices','A field team uses GPS, cameras, and probes to gather observations. Name the hardware category: ______.','Data collection',['collection','collecting data'],'All three are collection devices in the notes. They gather data from the real world.');
  fill('f8','Hardware & devices','A scanner or digitizer brings map information into the computer. Name the hardware category: ______.','Data input',['input'],'Scanners and digitizers are data input devices. They are distinct from the collection examples: GPS, cameras, and probes.');
  fill('f9','Hardware & devices','A GIS result is shown on a monitor or produced with a printer or plotter. Name the hardware category: ______.','Data output',['output'],'Monitors, printers, and plotters are output devices because they display or produce results.');
  fill('f10','Hardware & devices','Your notes group computers and hard drives under which hardware category? ______.','Data analysis and storage',['analysis and storage','data analysis storage','analysis storage','storage and analysis','data storage and analysis'],'Use the complete category: data analysis and storage. Computers process information and hard drives store it.');
  window.GIS_QUESTIONS = questions;
})();
